receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  memory_limiter:
    limit_mib: 100
    spike_limit_mib: 20
    check_interval: 5s

exporters:
  kafka:
    brokers: ['kafka:9093']
    topic: 'logs'
    encoding: raw

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [kafka]

  telemetry:
    logs:
      level: 'debug'